# Generated by Django 5.0.6 on 2024-05-28 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
                ('arabik', models.CharField(max_length=3000)),
                ('buchcharon', models.CharField(max_length=3000)),
                ('sura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcomapp.sura')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qcomapp.translator')),
            ],
        ),
    ]
